spring.application.name=terapeutico
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0

spring.datasource.username=postgres.ydafqfnfjmgbndbgqzpi
spring.datasource.password=estofado de aguacate

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.session.jdbc.initialize-schema=never